name: Link Checker Example Command
on: push
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: peter-evans/link-checker@v1
        id: lc
        with:
          args: -v -t 60 -c 16 -d /docs -r /docs
      - name: Output exit code
        run: exit ${{ steps.lc.outputs.exit_code }}
