name: Link Checker
on: push
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        env:
          LYCHEE_OUT: ./lychee/
        with:
          args: --timeout 60 ./**/*.md --format json
      - name: Count broken links
        if: always()
        run: |
            find .
            broken_max=10
            broken=$(grep ERROR ./lychee/out.md)
            broken_count=$(echo "$broken" | wc -l)

            if [ "$broken" -gt "$broken_max" ]; then
                echo "Number of broken links (${broken}) exceeds maximum allowed number (${broken_max})."
                echo "Broken links: "
                echo "$broken"
                exit 1
            else
                echo "Number of broken links (${broken}) less than or equal to maximum allowed number (${broken_max})."
                exit 0
            fi
