name: Link Checker
on: push
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.4
        env:
          LYCHEE_OUT: /github/workflow/
        with:
          args: --timeout 60 ./**/*.md
      - name: Count broken links
        if: always()
        run: |
            broken_max=10
            ls
            ls lychee
            cat ./lychee/out.md
            echo '==================================='
            broken=$(grep "Errors" ./lychee/out.md | cut -d ":" -f2)

            if [ "$broken" -gt "$broken_max" ]; then
                echo "Number of broken links (${broken}) exceeds maximum allowed number (${broken_max})."
                cat ./lychee/out.md
                exit 1
            else
                echo "Number of broken links (${broken}) less than or equal to maximum allowed number (${broken_max})."
                exit 0
            fi
